// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe9zVIUl-kNJ4e5rlZWZdtOwfS6OgX9xs',
    appId: '1:1060388608416:web:6c3372ddfc7b7f252f6cc5',
    messagingSenderId: '1060388608416',
    projectId: 'gaming-7f86e',
    authDomain: 'gaming-7f86e.firebaseapp.com',
    storageBucket: 'gaming-7f86e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwQv7KvnzcUUpB9IcgdVRg7GIA2-ZC8FQ',
    appId: '1:1060388608416:android:eefb14ecced34b192f6cc5',
    messagingSenderId: '1060388608416',
    projectId: 'gaming-7f86e',
    storageBucket: 'gaming-7f86e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBPKtaL-8ol6WjY3JJhbKmGLjEzNm4M9k',
    appId: '1:1060388608416:ios:3e483d6b868d69ce2f6cc5',
    messagingSenderId: '1060388608416',
    projectId: 'gaming-7f86e',
    storageBucket: 'gaming-7f86e.firebasestorage.app',
    iosBundleId: 'com.example.fl2Polintan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBPKtaL-8ol6WjY3JJhbKmGLjEzNm4M9k',
    appId: '1:1060388608416:ios:3e483d6b868d69ce2f6cc5',
    messagingSenderId: '1060388608416',
    projectId: 'gaming-7f86e',
    storageBucket: 'gaming-7f86e.firebasestorage.app',
    iosBundleId: 'com.example.fl2Polintan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe9zVIUl-kNJ4e5rlZWZdtOwfS6OgX9xs',
    appId: '1:1060388608416:web:b2cecf530d3282832f6cc5',
    messagingSenderId: '1060388608416',
    projectId: 'gaming-7f86e',
    authDomain: 'gaming-7f86e.firebaseapp.com',
    storageBucket: 'gaming-7f86e.firebasestorage.app',
  );

}